name: Build and Test

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  # Can use a build matrix here, finding all go.mod files and iterating.
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.20.5'
    - run: cd dalle && go build ./...
    - run: cd dalle && go fmt ./...
    - run: cd dalle && go test ./...